#!/usr/bin/env bash
#set -euo pipefail

. $(dirname $0)/ciutil
GITROOT=`git-root`

initstart=$(time-now)


# =============================================================================
# Setup
# =============================================================================
✨ "Setup: Create directories"
create-directories

✨ "Setup: Preinstall binaries"
preinstall-binaries

# =============================================================================
# DEBUG
# =============================================================================
✨ "Debug: System information"
show-system-information

✨ "Debug: Env variables"
dump-env

show-cache-structure
timestamp

# =============================================================================
# Install node_modules
# =============================================================================
if cat $GITROOT/.scripts/package.json | jq -e .dependencies &>/dev/null; then
  ✨ "pnpm install"

  cd $GITROOT/.scripts

  # Applying dirty fix for *not* including @types/* in the production ci
  cp pnpm-lock.yaml $RUNNER_TEMPDIR/
  grep -v "'@types/" $RUNNER_TEMPDIR/pnpm-lock.yaml >| pnpm-lock.yaml

  pnpm install \
    --frozen-lockfile \
    --production \
    --prefer-offline \
    --no-verify-store-integrity

  mv $RUNNER_TEMPDIR/pnpm-lock.yaml .
  timestamp

fi
